version: '3.7'
services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=netologytest
      - POSTGRES_USER=user
      - POSTGRES_DB=app_db